### ISSUE TITLE
If you're borrowing / building on other people's work, then you should credit them

### ISSUE THREAD

**Issue by clhenrick** [lblok/dapmap#1]
Not cool to blow away the `.git` directory and not mention authors of work you're using and attempting to show as your own work. Please credit the original authors of this work which can be found here: https://github.com/ANHD-NYC/SAMP

**Comment by lblok** [comment]
Hi Chris! Yes--this is me (Lucy Block) working on the new version for the upcoming DAP Map update. I made a parallel version so as not to accidentally destroy the original with my newbiness, and soon we'll migrate it over to this. I haven't updated the README file yet to reflect that that's what this is. I should probably do that and not assume no one ever sees anything I do.

**Comment by lblok** [comment]
Added a note to the top of README– @clhenrick does it clarify?

**Comment by clhenrick** [comment]
Thanks @jdgodchaux @lblok for letting me know, although @lblok you only credit NiJel in the README and not myself (another reason the original `git` history is useful)

Destroying the `.git` directory and committing the code in a new repository makes it appear that the code is now entirely the result of your own work to anyone looking at your repository, which is clearly not the case here. For code that has certain types of software licenses you could theoretically get into legal trouble as well.

Similar etiquette typically goes for any code you might copy and paste, it's always good to add a code comment that credits the original author.

This could have been avoided if instead you had forked the code which would have kept the commits of the original authors.

**Comment by lblok** [comment]
Sorry for the oversight, will fix tomorrow. Thanks for the tip on forking.
This was what I figured out how to do within my beginner understanding of
coding and general fear of Git, but it’s helpful to know that’s the reason
to fork. If there’s anything else I can do to remedy the situation, please
let me know.

**Comment by lblok** [comment]
Hi @clhenrick, please take a look and let me know if the attribution in the README is now accurate and complete and if there's anything else I can do to give you proper credit.

**Comment by clhenrick** [comment]
Hi @lblok thanks very much, looks good to me. Best of luck with the project and your journey into web development, I'm sure you'll do great!
